apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotify-backend
  template:
    metadata:
      labels:
        app: spotify-backend
    spec:
      containers:
        - name: spotify-backend
          image: spotify-backend:v1
          ports:
            - containerPort: 5000
